### ISSUE TITLE
Build for more arch

### ISSUE THREAD

**Issue by androw** [androw/docker-nsd#1]
@xkolk, if you're interested in building for more arch, I'll be happy to add.

Do not hesitate to open a PR!
I think it's easier if we have less images available.

**Comment by xkolk** [comment]
My reason for the fork was building for /latest instead of /edge. Extra
architectures were added just for testing the build procedure.
I think we should make a PR for platform list to be parsed from - with:

**Comment by androw** [comment]
Oups, should I've missed this change! Nevermind
